import js from '@eslint/js';
import tseslint from 'typescript-eslint';

export default tseslint.config(
  {
    ignores: [
      '**/node_modules/**',
      '**/.next/**',
      '**/dist/**',
      '**/coverage/**',
      'packages/db/migrations/**',
      // Generated by Next on every build.
      '**/next-env.d.ts',
      // The Stockfish build, downloaded by scripts/fetch-stockfish.mjs. Not ours to lint.
      'apps/web/public/engines/**',
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    // Build scripts are plain Node ESM, outside any tsconfig, so no-undef is live for them.
    files: ['scripts/**/*.mjs'],
    languageOptions: {
      globals: {
        Buffer: 'readonly',
        console: 'readonly',
        fetch: 'readonly',
        process: 'readonly',
      },
    },
  },
  {
    rules: {
      // The rule that keeps the LLM out of evaluation and the client out of authorisation is
      // architectural, not lintable — see CONTRIBUTING.md. These are the mechanical ones.
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      '@typescript-eslint/no-explicit-any': 'error',
      'no-console': 'off',
    },
  },
);
